version: 2
updates:
  - package-ecosystem: "npm"  # ou "github-actions", "docker" etc., dependendo do seu ambiente
    directory: "/"
    schedule:
      interval: "daily"  # ou "weekly", "monthly", etc.
    open-pull-requests-limit: 10  # número máximo de pull requests abertos
    labels:
      - "dependabot"  # opcional, para adicionar rótulos aos pull requests do Dependabot
      - "dependecies"
